In [1]:
import pandas as pd
import numpy as np
import requests
import os 
import pickle
from dotenv import load_dotenv
from datetime import datetime, time, timedelta
load_dotenv()

True

In [2]:
import requests
import re
from bs4 import BeautifulSoup
url_paises = 'https://statisticstimes.com/geography/countries-by-continents.php'
html_paises = requests.get(url_paises)

In [3]:
html_paises.status_code

200

In [4]:
sopa_paises = BeautifulSoup(html_paises.content, "html.parser")

In [5]:
paises = sopa_paises.find_all("table")
len(paises)
#paises[2]

3

In [6]:
lista_paises = paises[2]

In [7]:
# con esto sacamos todas las filas de nuestra tabla

len(lista_paises.find_all("tr"))

250

In [8]:
paises_dict = {
    'Country':[],
    'ISO_Code':[],
    'M49_Code':[],
    'Region1':[],
    'Region2':[],
    'Continent':[]
}

In [9]:
for f in lista_paises.find_all('tr')[1:]:
    columna = [elemento.text for elemento in f.find_all('td')]

    print(columna)

['1', 'Afghanistan', 'AFG', '004', 'Southern Asia', '', 'Asia']
['2', 'Åland Islands', 'ALA', '248', 'Northern Europe', '', 'Europe']
['3', 'Albania', 'ALB', '008', 'Southern Europe', '', 'Europe']
['4', 'Algeria', 'DZA', '012', 'Northern Africa', '', 'Africa']
['5', 'American Samoa', 'ASM', '016', 'Polynesia', '', 'Oceania']
['6', 'Andorra', 'AND', '020', 'Southern Europe', '', 'Europe']
['7', 'Angola', 'AGO', '024', 'Middle Africa', 'Sub-Saharan Africa', 'Africa']
['8', 'Anguilla', 'AIA', '660', 'Caribbean', 'Latin America and the Caribbean', 'North America']
['9', 'Antarctica', 'ATA', '010', 'Antarctica', '', 'Antarctica']
['10', 'Antigua and Barbuda', 'ATG', '028', 'Caribbean', 'Latin America and the Caribbean', 'North America']
['11', 'Argentina', 'ARG', '032', 'South America', 'Latin America and the Caribbean', 'South America']
['12', 'Armenia', 'ARM', '051', 'Western Asia', '', 'Asia']
['13', 'Aruba', 'ABW', '533', 'Caribbean', 'Latin America and the Caribbean', 'North America']
['14', 'Australia', 'AUS', '036', 'Australia and New Zealand', '', 'Oceania']
['15', 'Austria', 'AUT', '040', 'Western Europe', '', 'Europe']
['16', 'Azerbaijan', 'AZE', '031', 'Western Asia', '', 'Asia']
['17', 'Bahamas', 'BHS', '044', 'Caribbean', 'Latin America and the Caribbean', 'North America']
['18', 'Bahrain', 'BHR', '048', 'Western Asia', '', 'Asia']
['19', 'Bangladesh', 'BGD', '050', 'Southern Asia', '', 'Asia']
['20', 'Barbados', 'BRB', '052', 'Caribbean', 'Latin America and the Caribbean', 'North America']
['21', 'Belarus', 'BLR', '112', 'Eastern Europe', '', 'Europe']
['22', 'Belgium', 'BEL', '056', 'Western Europe', '', 'Europe']
['23', 'Belize', 'BLZ', '084', 'Central America', 'Latin America and the Caribbean', 'North America']
['24', 'Benin', 'BEN', '204', 'Western Africa', 'Sub-Saharan Africa', 'Africa']
['25', 'Bermuda', 'BMU', '060', 'Northern America', '', 'North America']
['26', 'Bhutan', 'BTN', '064', 'Southern Asia', '', 'Asia']
['27', 'Bolivia (Plurinational State of)', 'BOL', '068', 'South America', 'Latin America and the Caribbean', 'South America']
['28', 'Bonaire, Sint Eustatius and Saba', 'BES', '535', 'Caribbean', 'Latin America and the Caribbean', 'North America']
['29', 'Bosnia and Herzegovina', 'BIH', '070', 'Southern Europe', '', 'Europe']
['30', 'Botswana', 'BWA', '072', 'Southern Africa', 'Sub-Saharan Africa', 'Africa']
['31', 'Bouvet Island', 'BVT', '074', 'South America', 'Latin America and the Caribbean', 'South America']
['32', 'Brazil', 'BRA', '076', 'South America', 'Latin America and the Caribbean', 'South America']
['33', 'British Indian Ocean Territory', 'IOT', '086', 'Eastern Africa', 'Sub-Saharan Africa', 'Africa']
['34', 'British Virgin Islands', 'VGB', '092', 'Caribbean', 'Latin America and the Caribbean', 'North America']
['35', 'Brunei Darussalam', 'BRN', '096', 'South-eastern Asia', '', 'Asia']
['36', 'Bulgaria', 'BGR', '100', 'Eastern Europe', '', 'Europe']
['37', 'Burkina Faso', 'BFA', '854', 'Western Africa', 'Sub-Saharan Africa', 'Africa']
['38', 'Burundi', 'BDI', '108', 'Eastern Africa', 'Sub-Saharan Africa', 'Africa']
['39', 'Cabo Verde', 'CPV', '132', 'Western Africa', 'Sub-Saharan Africa', 'Africa']
['40', 'Cambodia', 'KHM', '116', 'South-eastern Asia', '', 'Asia']
['41', 'Cameroon', 'CMR', '120', 'Middle Africa', 'Sub-Saharan Africa', 'Africa']
['42', 'Canada', 'CAN', '124', 'Northern America', '', 'North America']
['43', 'Cayman Islands', 'CYM', '136', 'Caribbean', 'Latin America and the Caribbean', 'North America']
['44', 'Central African Republic', 'CAF', '140', 'Middle Africa', 'Sub-Saharan Africa', 'Africa']
['45', 'Chad', 'TCD', '148', 'Middle Africa', 'Sub-Saharan Africa', 'Africa']
['46', 'Chile', 'CHL', '152', 'South America', 'Latin America and the Caribbean', 'South America']
['47', 'China', 'CHN', '156', 'Eastern Asia', '', 'Asia']
['48', 'China, Hong Kong Special Administrative Region', 'HKG', '344', 'Eastern Asia', '', 'Asia']
['49', 'China, Macao Special Administrative Region', 'MAC', '446', 'Eastern Asia', '', 'Asia']
['50', 'Christmas Island', 'CXR', '162', 'Australia and New Zealand', '', 'Oceania']
['51', 'Cocos (Keeling) Islands', 'CCK', '166', 'Australia and New Zealand', '', 'Oceania']
['52', 'Colombia', 'COL', '170', 'South America', 'Latin America and the Caribbean', 'South America']
['53', 'Comoros', 'COM', '174', 'Eastern Africa', 'Sub-Saharan Africa', 'Africa']
['54', 'Congo', 'COG', '178', 'Middle Africa', 'Sub-Saharan Africa', 'Africa']
['55', 'Cook Islands', 'COK', '184', 'Polynesia', '', 'Oceania']
['56', 'Costa Rica', 'CRI', '188', 'Central America', 'Latin America and the Caribbean', 'North America']
['57', 'Côte d’Ivoire', 'CIV', '384', 'Western Africa', 'Sub-Saharan Africa', 'Africa']
['58', 'Croatia', 'HRV', '191', 'Southern Europe', '', 'Europe']
['59', 'Cuba', 'CUB', '192', 'Caribbean', 'Latin America and the Caribbean', 'North America']
['60', 'Curaçao', 'CUW', '531', 'Caribbean', 'Latin America and the Caribbean', 'North America']
['61', 'Cyprus', 'CYP', '196', 'Western Asia', '', 'Asia']
['62', 'Czechia', 'CZE', '203', 'Eastern Europe', '', 'Europe']
['63', "Democratic People's Republic of Korea", 'PRK', '408', 'Eastern Asia', '', 'Asia']
['64', 'Democratic Republic of the Congo', 'COD', '180', 'Middle Africa', 'Sub-Saharan Africa', 'Africa']
['65', 'Denmark', 'DNK', '208', 'Northern Europe', '', 'Europe']
['66', 'Djibouti', 'DJI', '262', 'Eastern Africa', 'Sub-Saharan Africa', 'Africa']
['67', 'Dominica', 'DMA', '212', 'Caribbean', 'Latin America and the Caribbean', 'North America']
['68', 'Dominican Republic', 'DOM', '214', 'Caribbean', 'Latin America and the Caribbean', 'North America']
['69', 'Ecuador', 'ECU', '218', 'South America', 'Latin America and the Caribbean', 'South America']
['70', 'Egypt', 'EGY', '818', 'Northern Africa', '', 'Africa']
['71', 'El Salvador', 'SLV', '222', 'Central America', 'Latin America and the Caribbean', 'North America']
['72', 'Equatorial Guinea', 'GNQ', '226', 'Middle Africa', 'Sub-Saharan Africa', 'Africa']
['73', 'Eritrea', 'ERI', '232', 'Eastern Africa', 'Sub-Saharan Africa', 'Africa']
['74', 'Estonia', 'EST', '233', 'Northern Europe', '', 'Europe']
['75', 'Eswatini', 'SWZ', '748', 'Southern Africa', 'Sub-Saharan Africa', 'Africa']
['76', 'Ethiopia', 'ETH', '231', 'Eastern Africa', 'Sub-Saharan Africa', 'Africa']
['77', 'Falkland Islands (Malvinas)', 'FLK', '238', 'South America', 'Latin America and the Caribbean', 'South America']
['78', 'Faroe Islands', 'FRO', '234', 'Northern Europe', '', 'Europe']
['79', 'Fiji', 'FJI', '242', 'Melanesia', '', 'Oceania']
['80', 'Finland', 'FIN', '246', 'Northern Europe', '', 'Europe']
['81', 'France', 'FRA', '250', 'Western Europe', '', 'Europe']
['82', 'French Guiana', 'GUF', '254', 'South America', 'Latin America and the Caribbean', 'South America']
['83', 'French Polynesia', 'PYF', '258', 'Polynesia', '', 'Oceania']
['84', 'French Southern Territories', 'ATF', '260', 'Eastern Africa', 'Sub-Saharan Africa', 'Africa']
['85', 'Gabon', 'GAB', '266', 'Middle Africa', 'Sub-Saharan Africa', 'Africa']
['86', 'Gambia', 'GMB', '270', 'Western Africa', 'Sub-Saharan Africa', 'Africa']
['87', 'Georgia', 'GEO', '268', 'Western Asia', '', 'Asia']
['88', 'Germany', 'DEU', '276', 'Western Europe', '', 'Europe']
['89', 'Ghana', 'GHA', '288', 'Western Africa', 'Sub-Saharan Africa', 'Africa']
['90', 'Gibraltar', 'GIB', '292', 'Southern Europe', '', 'Europe']
['91', 'Greece', 'GRC', '300', 'Southern Europe', '', 'Europe']
['92', 'Greenland', 'GRL', '304', 'Northern America', '', 'North America']
['93', 'Grenada', 'GRD', '308', 'Caribbean', 'Latin America and the Caribbean', 'North America']
['94', 'Guadeloupe', 'GLP', '312', 'Caribbean', 'Latin America and the Caribbean', 'North America']
['95', 'Guam', 'GUM', '316', 'Micronesia', '', 'Oceania']
['96', 'Guatemala', 'GTM', '320', 'Central America', 'Latin America and the Caribbean', 'North America']
['97', 'Guernsey', 'GGY', '831', 'Northern Europe', 'Channel Islands', 'Europe']
['98', 'Guinea', 'GIN', '324', 'Western Africa', 'Sub-Saharan Africa', 'Africa']
['99', 'Guinea-Bissau', 'GNB', '624', 'Western Africa', 'Sub-Saharan Africa', 'Africa']
['100', 'Guyana', 'GUY', '328', 'South America', 'Latin America and the Caribbean', 'South America']
['101', 'Haiti', 'HTI', '332', 'Caribbean', 'Latin America and the Caribbean', 'North America']
['102', 'Heard Island and McDonald Islands', 'HMD', '334', 'Australia and New Zealand', '', 'Oceania']
['103', 'Holy See', 'VAT', '336', 'Southern Europe', '', 'Europe']
['104', 'Honduras', 'HND', '340', 'Central America', 'Latin America and the Caribbean', 'North America']
['105', 'Hungary', 'HUN', '348', 'Eastern Europe', '', 'Europe']
['106', 'Iceland', 'ISL', '352', 'Northern Europe', '', 'Europe']
['107', 'India', 'IND', '356', 'Southern Asia', '', 'Asia']
['108', 'Indonesia', 'IDN', '360', 'South-eastern Asia', '', 'Asia']
['109', 'Iran (Islamic Republic of)', 'IRN', '364', 'Southern Asia', '', 'Asia']
['110', 'Iraq', 'IRQ', '368', 'Western Asia', '', 'Asia']
['111', 'Ireland', 'IRL', '372', 'Northern Europe', '', 'Europe']
['112', 'Isle of Man', 'IMN', '833', 'Northern Europe', '', 'Europe']
['113', 'Israel', 'ISR', '376', 'Western Asia', '', 'Asia']
['114', 'Italy', 'ITA', '380', 'Southern Europe', '', 'Europe']
['115', 'Jamaica', 'JAM', '388', 'Caribbean', 'Latin America and the Caribbean', 'North America']
['116', 'Japan', 'JPN', '392', 'Eastern Asia', '', 'Asia']
['117', 'Jersey', 'JEY', '832', 'Northern Europe', 'Channel Islands', 'Europe']
['118', 'Jordan', 'JOR', '400', 'Western Asia', '', 'Asia']
['119', 'Kazakhstan', 'KAZ', '398', 'Central Asia', '', 'Asia']
['120', 'Kenya', 'KEN', '404', 'Eastern Africa', 'Sub-Saharan Africa', 'Africa']
['121', 'Kiribati', 'KIR', '296', 'Micronesia', '', 'Oceania']
['122', 'Kuwait', 'KWT', '414', 'Western Asia', '', 'Asia']
['123', 'Kyrgyzstan', 'KGZ', '417', 'Central Asia', '', 'Asia']
['124', "Lao People's Democratic Republic", 'LAO', '418', 'South-eastern Asia', '', 'Asia']
['125', 'Latvia', 'LVA', '428', 'Northern Europe', '', 'Europe']
['126', 'Lebanon', 'LBN', '422', 'Western Asia', '', 'Asia']
['127', 'Lesotho', 'LSO', '426', 'Southern Africa', 'Sub-Saharan Africa', 'Africa']
['128', 'Liberia', 'LBR', '430', 'Western Africa', 'Sub-Saharan Africa', 'Africa']
['129', 'Libya', 'LBY', '434', 'Northern Africa', '', 'Africa']
['130', 'Liechtenstein', 'LIE', '438', 'Western Europe', '', 'Europe']
['131', 'Lithuania', 'LTU', '440', 'Northern Europe', '', 'Europe']
['132', 'Luxembourg', 'LUX', '442', 'Western Europe', '', 'Europe']
['133', 'Madagascar', 'MDG', '450', 'Eastern Africa', 'Sub-Saharan Africa', 'Africa']
['134', 'Malawi', 'MWI', '454', 'Eastern Africa', 'Sub-Saharan Africa', 'Africa']
['135', 'Malaysia', 'MYS', '458', 'South-eastern Asia', '', 'Asia']
['136', 'Maldives', 'MDV', '462', 'Southern Asia', '', 'Asia']
['137', 'Mali', 'MLI', '466', 'Western Africa', 'Sub-Saharan Africa', 'Africa']
['138', 'Malta', 'MLT', '470', 'Southern Europe', '', 'Europe']
['139', 'Marshall Islands', 'MHL', '584', 'Micronesia', '', 'Oceania']
['140', 'Martinique', 'MTQ', '474', 'Caribbean', 'Latin America and the Caribbean', 'North America']
['141', 'Mauritania', 'MRT', '478', 'Western Africa', 'Sub-Saharan Africa', 'Africa']
['142', 'Mauritius', 'MUS', '480', 'Eastern Africa', 'Sub-Saharan Africa', 'Africa']
['143', 'Mayotte', 'MYT', '175', 'Eastern Africa', 'Sub-Saharan Africa', 'Africa']
['144', 'Mexico', 'MEX', '484', 'Central America', 'Latin America and the Caribbean', 'North America']
['145', 'Micronesia (Federated States of)', 'FSM', '583', 'Micronesia', '', 'Oceania']
['146', 'Monaco', 'MCO', '492', 'Western Europe', '', 'Europe']
['147', 'Mongolia', 'MNG', '496', 'Eastern Asia', '', 'Asia']
['148', 'Montenegro', 'MNE', '499', 'Southern Europe', '', 'Europe']
['149', 'Montserrat', 'MSR', '500', 'Caribbean', 'Latin America and the Caribbean', 'North America']
['150', 'Morocco', 'MAR', '504', 'Northern Africa', '', 'Africa']
['151', 'Mozambique', 'MOZ', '508', 'Eastern Africa', 'Sub-Saharan Africa', 'Africa']
['152', 'Myanmar', 'MMR', '104', 'South-eastern Asia', '', 'Asia']
['153', 'Namibia', 'NAM', '516', 'Southern Africa', 'Sub-Saharan Africa', 'Africa']
['154', 'Nauru', 'NRU', '520', 'Micronesia', '', 'Oceania']
['155', 'Nepal', 'NPL', '524', 'Southern Asia', '', 'Asia']
['156', 'Netherlands', 'NLD', '528', 'Western Europe', '', 'Europe']
['157', 'New Caledonia', 'NCL', '540', 'Melanesia', '', 'Oceania']
['158', 'New Zealand', 'NZL', '554', 'Australia and New Zealand', '', 'Oceania']
['159', 'Nicaragua', 'NIC', '558', 'Central America', 'Latin America and the Caribbean', 'North America']
['160', 'Niger', 'NER', '562', 'Western Africa', 'Sub-Saharan Africa', 'Africa']
['161', 'Nigeria', 'NGA', '566', 'Western Africa', 'Sub-Saharan Africa', 'Africa']
['162', 'Niue', 'NIU', '570', 'Polynesia', '', 'Oceania']
['163', 'Norfolk Island', 'NFK', '574', 'Australia and New Zealand', '', 'Oceania']
['164', 'North Macedonia', 'MKD', '807', 'Southern Europe', '', 'Europe']
['165', 'Northern Mariana Islands', 'MNP', '580', 'Micronesia', '', 'Oceania']
['166', 'Norway', 'NOR', '578', 'Northern Europe', '', 'Europe']
['167', 'Oman', 'OMN', '512', 'Western Asia', '', 'Asia']
['168', 'Pakistan', 'PAK', '586', 'Southern Asia', '', 'Asia']
['169', 'Palau', 'PLW', '585', 'Micronesia', '', 'Oceania']
['170', 'Panama', 'PAN', '591', 'Central America', 'Latin America and the Caribbean', 'North America']
['171', 'Papua New Guinea', 'PNG', '598', 'Melanesia', '', 'Oceania']
['172', 'Paraguay', 'PRY', '600', 'South America', 'Latin America and the Caribbean', 'South America']
['173', 'Peru', 'PER', '604', 'South America', 'Latin America and the Caribbean', 'South America']
['174', 'Philippines', 'PHL', '608', 'South-eastern Asia', '', 'Asia']
['175', 'Pitcairn', 'PCN', '612', 'Polynesia', '', 'Oceania']
['176', 'Poland', 'POL', '616', 'Eastern Europe', '', 'Europe']
['177', 'Portugal', 'PRT', '620', 'Southern Europe', '', 'Europe']
['178', 'Puerto Rico', 'PRI', '630', 'Caribbean', 'Latin America and the Caribbean', 'North America']
['179', 'Qatar', 'QAT', '634', 'Western Asia', '', 'Asia']
['180', 'Republic of Korea', 'KOR', '410', 'Eastern Asia', '', 'Asia']
['181', 'Republic of Moldova', 'MDA', '498', 'Eastern Europe', '', 'Europe']
['182', 'Réunion', 'REU', '638', 'Eastern Africa', 'Sub-Saharan Africa', 'Africa']
['183', 'Romania', 'ROU', '642', 'Eastern Europe', '', 'Europe']
['184', 'Russian Federation', 'RUS', '643', 'Eastern Europe', '', 'Europe']
['185', 'Rwanda', 'RWA', '646', 'Eastern Africa', 'Sub-Saharan Africa', 'Africa']
['186', 'Saint Barthélemy', 'BLM', '652', 'Caribbean', 'Latin America and the Caribbean', 'North America']
['187', 'Saint Helena', 'SHN', '654', 'Western Africa', 'Sub-Saharan Africa', 'Africa']
['188', 'Saint Kitts and Nevis', 'KNA', '659', 'Caribbean', 'Latin America and the Caribbean', 'North America']
['189', 'Saint Lucia', 'LCA', '662', 'Caribbean', 'Latin America and the Caribbean', 'North America']
['190', 'Saint Martin (French Part)', 'MAF', '663', 'Caribbean', 'Latin America and the Caribbean', 'North America']
['191', 'Saint Pierre and Miquelon', 'SPM', '666', 'Northern America', '', 'North America']
['192', 'Saint Vincent and the Grenadines', 'VCT', '670', 'Caribbean', 'Latin America and the Caribbean', 'North America']
['193', 'Samoa', 'WSM', '882', 'Polynesia', '', 'Oceania']
['194', 'San Marino', 'SMR', '674', 'Southern Europe', '', 'Europe']
['195', 'Sao Tome and Principe', 'STP', '678', 'Middle Africa', 'Sub-Saharan Africa', 'Africa']
['196', 'Sark', ' ', '680', 'Northern Europe', 'Channel Islands', 'Europe']
['197', 'Saudi Arabia', 'SAU', '682', 'Western Asia', '', 'Asia']
['198', 'Senegal', 'SEN', '686', 'Western Africa', 'Sub-Saharan Africa', 'Africa']
['199', 'Serbia', 'SRB', '688', 'Southern Europe', '', 'Europe']
['200', 'Seychelles', 'SYC', '690', 'Eastern Africa', 'Sub-Saharan Africa', 'Africa']
['201', 'Sierra Leone', 'SLE', '694', 'Western Africa', 'Sub-Saharan Africa', 'Africa']
['202', 'Singapore', 'SGP', '702', 'South-eastern Asia', '', 'Asia']
['203', 'Sint Maarten (Dutch part)', 'SXM', '534', 'Caribbean', 'Latin America and the Caribbean', 'North America']
['204', 'Slovakia', 'SVK', '703', 'Eastern Europe', '', 'Europe']
['205', 'Slovenia', 'SVN', '705', 'Southern Europe', '', 'Europe']
['206', 'Solomon Islands', 'SLB', '090', 'Melanesia', '', 'Oceania']
['207', 'Somalia', 'SOM', '706', 'Eastern Africa', 'Sub-Saharan Africa', 'Africa']
['208', 'South Africa', 'ZAF', '710', 'Southern Africa', 'Sub-Saharan Africa', 'Africa']
['209', 'South Georgia and the South Sandwich Islands', 'SGS', '239', 'South America', 'Latin America and the Caribbean', 'South America']
['210', 'South Sudan', 'SSD', '728', 'Eastern Africa', 'Sub-Saharan Africa', 'Africa']
['211', 'Spain', 'ESP', '724', 'Southern Europe', '', 'Europe']
['212', 'Sri Lanka', 'LKA', '144', 'Southern Asia', '', 'Asia']
['213', 'State of Palestine', 'PSE', '275', 'Western Asia', '', 'Asia']
['214', 'Sudan', 'SDN', '729', 'Northern Africa', '', 'Africa']
['215', 'Suriname', 'SUR', '740', 'South America', 'Latin America and the Caribbean', 'South America']
['216', 'Svalbard and Jan Mayen Islands', 'SJM', '744', 'Northern Europe', '', 'Europe']
['217', 'Sweden', 'SWE', '752', 'Northern Europe', '', 'Europe']
['218', 'Switzerland', 'CHE', '756', 'Western Europe', '', 'Europe']
['219', 'Syrian Arab Republic', 'SYR', '760', 'Western Asia', '', 'Asia']
['220', 'Tajikistan', 'TJK', '762', 'Central Asia', '', 'Asia']
['221', 'Thailand', 'THA', '764', 'South-eastern Asia', '', 'Asia']
['222', 'Timor-Leste', 'TLS', '626', 'South-eastern Asia', '', 'Asia']
['223', 'Togo', 'TGO', '768', 'Western Africa', 'Sub-Saharan Africa', 'Africa']
['224', 'Tokelau', 'TKL', '772', 'Polynesia', '', 'Oceania']
['225', 'Tonga', 'TON', '776', 'Polynesia', '', 'Oceania']
['226', 'Trinidad and Tobago', 'TTO', '780', 'Caribbean', 'Latin America and the Caribbean', 'North America']
['227', 'Tunisia', 'TUN', '788', 'Northern Africa', '', 'Africa']
['228', 'Turkey', 'TUR', '792', 'Western Asia', '', 'Asia']
['229', 'Turkmenistan', 'TKM', '795', 'Central Asia', '', 'Asia']
['230', 'Turks and Caicos Islands', 'TCA', '796', 'Caribbean', 'Latin America and the Caribbean', 'North America']
['231', 'Tuvalu', 'TUV', '798', 'Polynesia', '', 'Oceania']
['232', 'Uganda', 'UGA', '800', 'Eastern Africa', 'Sub-Saharan Africa', 'Africa']
['233', 'Ukraine', 'UKR', '804', 'Eastern Europe', '', 'Europe']
['234', 'United Arab Emirates', 'ARE', '784', 'Western Asia', '', 'Asia']
['235', 'United Kingdom of Great Britain and Northern Ireland', 'GBR', '826', 'Northern Europe', '', 'Europe']
['236', 'United Republic of Tanzania', 'TZA', '834', 'Eastern Africa', 'Sub-Saharan Africa', 'Africa']
['237', 'United States Minor Outlying Islands', 'UMI', '581', 'Micronesia', '', 'Oceania']
['238', 'United States of America', 'USA', '840', 'Northern America', '', 'North America']
['239', 'United States Virgin Islands', 'VIR', '850', 'Caribbean', 'Latin America and the Caribbean', 'North America']
['240', 'Uruguay', 'URY', '858', 'South America', 'Latin America and the Caribbean', 'South America']
['241', 'Uzbekistan', 'UZB', '860', 'Central Asia', '', 'Asia']
['242', 'Vanuatu', 'VUT', '548', 'Melanesia', '', 'Oceania']
['243', 'Venezuela (Bolivarian Republic of)', 'VEN', '862', 'South America', 'Latin America and the Caribbean', 'South America']
['244', 'Viet Nam', 'VNM', '704', 'South-eastern Asia', '', 'Asia']
['245', 'Wallis and Futuna Islands', 'WLF', '876', 'Polynesia', '', 'Oceania']
['246', 'Western Sahara', 'ESH', '732', 'Northern Africa', '', 'Africa']
['247', 'Yemen', 'YEM', '887', 'Western Asia', '', 'Asia']
['248', 'Zambia', 'ZMB', '894', 'Eastern Africa', 'Sub-Saharan Africa', 'Africa']
['249', 'Zimbabwe', 'ZWE', '716', 'Eastern Africa', 'Sub-Saharan Africa', 'Africa']

In [10]:
keys = paises_dict.keys()
for f in lista_paises.find_all('tr')[1:]:
    columna = [elemento.text for elemento in f.find_all('td')]
    
    for num, key in zip(range(1, len(columna)), keys):
        
        paises_dict[key].append(columna[num])

In [11]:
paises_dict

{'Country': ['Afghanistan',
  'Åland Islands',
  'Albania',
  'Algeria',
  'American Samoa',
  'Andorra',
  'Angola',
  'Anguilla',
  'Antarctica',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia',
  'Aruba',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bermuda',
  'Bhutan',
  'Bolivia (Plurinational State of)',
  'Bonaire, Sint Eustatius and Saba',
  'Bosnia and Herzegovina',
  'Botswana',
  'Bouvet Island',
  'Brazil',
  'British Indian Ocean Territory',
  'British Virgin Islands',
  'Brunei Darussalam',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cabo Verde',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Cayman Islands',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'China, Hong Kong Special Administrative Region',
  'China, Macao Special Administrative Region',
  'Christmas Island',
  'Cocos (Keeling) Islands',
  'Colombia',
  'Comoros',
  'Congo',
  'Cook Islands',
  'Costa Rica',
  'Côte d’Ivoire',
  'Croatia',
  'Cuba',
  'Curaçao',
  'Cyprus',
  'Czechia',
  "Democratic People's Republic of Korea",
  'Democratic Republic of the Congo',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Eswatini',
  'Ethiopia',
  'Falkland Islands (Malvinas)',
  'Faroe Islands',
  'Fiji',
  'Finland',
  'France',
  'French Guiana',
  'French Polynesia',
  'French Southern Territories',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Gibraltar',
  'Greece',
  'Greenland',
  'Grenada',
  'Guadeloupe',
  'Guam',
  'Guatemala',
  'Guernsey',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Heard Island and McDonald Islands',
  'Holy See',
  'Honduras',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran (Islamic Republic of)',
  'Iraq',
  'Ireland',
  'Isle of Man',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jersey',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'Kuwait',
  'Kyrgyzstan',
  "Lao People's Democratic Republic",
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Martinique',
  'Mauritania',
  'Mauritius',
  'Mayotte',
  'Mexico',
  'Micronesia (Federated States of)',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Montserrat',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands',
  'New Caledonia',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'Niue',
  'Norfolk Island',
  'North Macedonia',
  'Northern Mariana Islands',
  'Norway',
  'Oman',
  'Pakistan',
  'Palau',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Pitcairn',
  'Poland',
  'Portugal',
  'Puerto Rico',
  'Qatar',
  'Republic of Korea',
  'Republic of Moldova',
  'Réunion',
  'Romania',
  'Russian Federation',
  'Rwanda',
  'Saint Barthélemy',
  'Saint Helena',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Martin (French Part)',
  'Saint Pierre and Miquelon',
  'Saint Vincent and the Grenadines',
  'Samoa',
  'San Marino',
  'Sao Tome and Principe',
  'Sark',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Sint Maarten (Dutch part)',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'South Georgia and the South Sandwich Islands',
  'South Sudan',
  'Spain',
  'Sri Lanka',
  'State of Palestine',
  'Sudan',
  'Suriname',
  'Svalbard and Jan Mayen Islands',
  'Sweden',
  'Switzerland',
  'Syrian Arab Republic',
  'Tajikistan',
  'Thailand',
  'Timor-Leste',
  'Togo',
  'Tokelau',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Turks and Caicos Islands',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom of Great Britain and Northern Ireland',
  'United Republic of Tanzania',
  'United States Minor Outlying Islands',
  'United States of America',
  'United States Virgin Islands',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Venezuela (Bolivarian Republic of)',
  'Viet Nam',
  'Wallis and Futuna Islands',
  'Western Sahara',
  'Yemen',
  'Zambia',
  'Zimbabwe'],
 'ISO_Code': ['AFG',
  'ALA',
  'ALB',
  'DZA',
  'ASM',
  'AND',
  'AGO',
  'AIA',
  'ATA',
  'ATG',
  'ARG',
  'ARM',
  'ABW',
  'AUS',
  'AUT',
  'AZE',
  'BHS',
  'BHR',
  'BGD',
  'BRB',
  'BLR',
  'BEL',
  'BLZ',
  'BEN',
  'BMU',
  'BTN',
  'BOL',
  'BES',
  'BIH',
  'BWA',
  'BVT',
  'BRA',
  'IOT',
  'VGB',
  'BRN',
  'BGR',
  'BFA',
  'BDI',
  'CPV',
  'KHM',
  'CMR',
  'CAN',
  'CYM',
  'CAF',
  'TCD',
  'CHL',
  'CHN',
  'HKG',
  'MAC',
  'CXR',
  'CCK',
  'COL',
  'COM',
  'COG',
  'COK',
  'CRI',
  'CIV',
  'HRV',
  'CUB',
  'CUW',
  'CYP',
  'CZE',
  'PRK',
  'COD',
  'DNK',
  'DJI',
  'DMA',
  'DOM',
  'ECU',
  'EGY',
  'SLV',
  'GNQ',
  'ERI',
  'EST',
  'SWZ',
  'ETH',
  'FLK',
  'FRO',
  'FJI',
  'FIN',
  'FRA',
  'GUF',
  'PYF',
  'ATF',
  'GAB',
  'GMB',
  'GEO',
  'DEU',
  'GHA',
  'GIB',
  'GRC',
  'GRL',
  'GRD',
  'GLP',
  'GUM',
  'GTM',
  'GGY',
  'GIN',
  'GNB',
  'GUY',
  'HTI',
  'HMD',
  'VAT',
  'HND',
  'HUN',
  'ISL',
  'IND',
  'IDN',
  'IRN',
  'IRQ',
  'IRL',
  'IMN',
  'ISR',
  'ITA',
  'JAM',
  'JPN',
  'JEY',
  'JOR',
  'KAZ',
  'KEN',
  'KIR',
  'KWT',
  'KGZ',
  'LAO',
  'LVA',
  'LBN',
  'LSO',
  'LBR',
  'LBY',
  'LIE',
  'LTU',
  'LUX',
  'MDG',
  'MWI',
  'MYS',
  'MDV',
  'MLI',
  'MLT',
  'MHL',
  'MTQ',
  'MRT',
  'MUS',
  'MYT',
  'MEX',
  'FSM',
  'MCO',
  'MNG',
  'MNE',
  'MSR',
  'MAR',
  'MOZ',
  'MMR',
  'NAM',
  'NRU',
  'NPL',
  'NLD',
  'NCL',
  'NZL',
  'NIC',
  'NER',
  'NGA',
  'NIU',
  'NFK',
  'MKD',
  'MNP',
  'NOR',
  'OMN',
  'PAK',
  'PLW',
  'PAN',
  'PNG',
  'PRY',
  'PER',
  'PHL',
  'PCN',
  'POL',
  'PRT',
  'PRI',
  'QAT',
  'KOR',
  'MDA',
  'REU',
  'ROU',
  'RUS',
  'RWA',
  'BLM',
  'SHN',
  'KNA',
  'LCA',
  'MAF',
  'SPM',
  'VCT',
  'WSM',
  'SMR',
  'STP',
  ' ',
  'SAU',
  'SEN',
  'SRB',
  'SYC',
  'SLE',
  'SGP',
  'SXM',
  'SVK',
  'SVN',
  'SLB',
  'SOM',
  'ZAF',
  'SGS',
  'SSD',
  'ESP',
  'LKA',
  'PSE',
  'SDN',
  'SUR',
  'SJM',
  'SWE',
  'CHE',
  'SYR',
  'TJK',
  'THA',
  'TLS',
  'TGO',
  'TKL',
  'TON',
  'TTO',
  'TUN',
  'TUR',
  'TKM',
  'TCA',
  'TUV',
  'UGA',
  'UKR',
  'ARE',
  'GBR',
  'TZA',
  'UMI',
  'USA',
  'VIR',
  'URY',
  'UZB',
  'VUT',
  'VEN',
  'VNM',
  'WLF',
  'ESH',
  'YEM',
  'ZMB',
  'ZWE'],
 'M49_Code': ['004',
  '248',
  '008',
  '012',
  '016',
  '020',
  '024',
  '660',
  '010',
  '028',
  '032',
  '051',
  '533',
  '036',
  '040',
  '031',
  '044',
  '048',
  '050',
  '052',
  '112',
  '056',
  '084',
  '204',
  '060',
  '064',
  '068',
  '535',
  '070',
  '072',
  '074',
  '076',
  '086',
  '092',
  '096',
  '100',
  '854',
  '108',
  '132',
  '116',
  '120',
  '124',
  '136',
  '140',
  '148',
  '152',
  '156',
  '344',
  '446',
  '162',
  '166',
  '170',
  '174',
  '178',
  '184',
  '188',
  '384',
  '191',
  '192',
  '531',
  '196',
  '203',
  '408',
  '180',
  '208',
  '262',
  '212',
  '214',
  '218',
  '818',
  '222',
  '226',
  '232',
  '233',
  '748',
  '231',
  '238',
  '234',
  '242',
  '246',
  '250',
  '254',
  '258',
  '260',
  '266',
  '270',
  '268',
  '276',
  '288',
  '292',
  '300',
  '304',
  '308',
  '312',
  '316',
  '320',
  '831',
  '324',
  '624',
  '328',
  '332',
  '334',
  '336',
  '340',
  '348',
  '352',
  '356',
  '360',
  '364',
  '368',
  '372',
  '833',
  '376',
  '380',
  '388',
  '392',
  '832',
  '400',
  '398',
  '404',
  '296',
  '414',
  '417',
  '418',
  '428',
  '422',
  '426',
  '430',
  '434',
  '438',
  '440',
  '442',
  '450',
  '454',
  '458',
  '462',
  '466',
  '470',
  '584',
  '474',
  '478',
  '480',
  '175',
  '484',
  '583',
  '492',
  '496',
  '499',
  '500',
  '504',
  '508',
  '104',
  '516',
  '520',
  '524',
  '528',
  '540',
  '554',
  '558',
  '562',
  '566',
  '570',
  '574',
  '807',
  '580',
  '578',
  '512',
  '586',
  '585',
  '591',
  '598',
  '600',
  '604',
  '608',
  '612',
  '616',
  '620',
  '630',
  '634',
  '410',
  '498',
  '638',
  '642',
  '643',
  '646',
  '652',
  '654',
  '659',
  '662',
  '663',
  '666',
  '670',
  '882',
  '674',
  '678',
  '680',
  '682',
  '686',
  '688',
  '690',
  '694',
  '702',
  '534',
  '703',
  '705',
  '090',
  '706',
  '710',
  '239',
  '728',
  '724',
  '144',
  '275',
  '729',
  '740',
  '744',
  '752',
  '756',
  '760',
  '762',
  '764',
  '626',
  '768',
  '772',
  '776',
  '780',
  '788',
  '792',
  '795',
  '796',
  '798',
  '800',
  '804',
  '784',
  '826',
  '834',
  '581',
  '840',
  '850',
  '858',
  '860',
  '548',
  '862',
  '704',
  '876',
  '732',
  '887',
  '894',
  '716'],
 'Region1': ['Southern Asia',
  'Northern Europe',
  'Southern Europe',
  'Northern Africa',
  'Polynesia',
  'Southern Europe',
  'Middle Africa',
  'Caribbean',
  'Antarctica',
  'Caribbean',
  'South America',
  'Western Asia',
  'Caribbean',
  'Australia and New Zealand',
  'Western Europe',
  'Western Asia',
  'Caribbean',
  'Western Asia',
  'Southern Asia',
  'Caribbean',
  'Eastern Europe',
  'Western Europe',
  'Central America',
  'Western Africa',
  'Northern America',
  'Southern Asia',
  'South America',
  'Caribbean',
  'Southern Europe',
  'Southern Africa',
  'South America',
  'South America',
  'Eastern Africa',
  'Caribbean',
  'South-eastern Asia',
  'Eastern Europe',
  'Western Africa',
  'Eastern Africa',
  'Western Africa',
  'South-eastern Asia',
  'Middle Africa',
  'Northern America',
  'Caribbean',
  'Middle Africa',
  'Middle Africa',
  'South America',
  'Eastern Asia',
  'Eastern Asia',
  'Eastern Asia',
  'Australia and New Zealand',
  'Australia and New Zealand',
  'South America',
  'Eastern Africa',
  'Middle Africa',
  'Polynesia',
  'Central America',
  'Western Africa',
  'Southern Europe',
  'Caribbean',
  'Caribbean',
  'Western Asia',
  'Eastern Europe',
  'Eastern Asia',
  'Middle Africa',
  'Northern Europe',
  'Eastern Africa',
  'Caribbean',
  'Caribbean',
  'South America',
  'Northern Africa',
  'Central America',
  'Middle Africa',
  'Eastern Africa',
  'Northern Europe',
  'Southern Africa',
  'Eastern Africa',
  'South America',
  'Northern Europe',
  'Melanesia',
  'Northern Europe',
  'Western Europe',
  'South America',
  'Polynesia',
  'Eastern Africa',
  'Middle Africa',
  'Western Africa',
  'Western Asia',
  'Western Europe',
  'Western Africa',
  'Southern Europe',
  'Southern Europe',
  'Northern America',
  'Caribbean',
  'Caribbean',
  'Micronesia',
  'Central America',
  'Northern Europe',
  'Western Africa',
  'Western Africa',
  'South America',
  'Caribbean',
  'Australia and New Zealand',
  'Southern Europe',
  'Central America',
  'Eastern Europe',
  'Northern Europe',
  'Southern Asia',
  'South-eastern Asia',
  'Southern Asia',
  'Western Asia',
  'Northern Europe',
  'Northern Europe',
  'Western Asia',
  'Southern Europe',
  'Caribbean',
  'Eastern Asia',
  'Northern Europe',
  'Western Asia',
  'Central Asia',
  'Eastern Africa',
  'Micronesia',
  'Western Asia',
  'Central Asia',
  'South-eastern Asia',
  'Northern Europe',
  'Western Asia',
  'Southern Africa',
  'Western Africa',
  'Northern Africa',
  'Western Europe',
  'Northern Europe',
  'Western Europe',
  'Eastern Africa',
  'Eastern Africa',
  'South-eastern Asia',
  'Southern Asia',
  'Western Africa',
  'Southern Europe',
  'Micronesia',
  'Caribbean',
  'Western Africa',
  'Eastern Africa',
  'Eastern Africa',
  'Central America',
  'Micronesia',
  'Western Europe',
  'Eastern Asia',
  'Southern Europe',
  'Caribbean',
  'Northern Africa',
  'Eastern Africa',
  'South-eastern Asia',
  'Southern Africa',
  'Micronesia',
  'Southern Asia',
  'Western Europe',
  'Melanesia',
  'Australia and New Zealand',
  'Central America',
  'Western Africa',
  'Western Africa',
  'Polynesia',
  'Australia and New Zealand',
  'Southern Europe',
  'Micronesia',
  'Northern Europe',
  'Western Asia',
  'Southern Asia',
  'Micronesia',
  'Central America',
  'Melanesia',
  'South America',
  'South America',
  'South-eastern Asia',
  'Polynesia',
  'Eastern Europe',
  'Southern Europe',
  'Caribbean',
  'Western Asia',
  'Eastern Asia',
  'Eastern Europe',
  'Eastern Africa',
  'Eastern Europe',
  'Eastern Europe',
  'Eastern Africa',
  'Caribbean',
  'Western Africa',
  'Caribbean',
  'Caribbean',
  'Caribbean',
  'Northern America',
  'Caribbean',
  'Polynesia',
  'Southern Europe',
  'Middle Africa',
  'Northern Europe',
  'Western Asia',
  'Western Africa',
  'Southern Europe',
  'Eastern Africa',
  'Western Africa',
  'South-eastern Asia',
  'Caribbean',
  'Eastern Europe',
  'Southern Europe',
  'Melanesia',
  'Eastern Africa',
  'Southern Africa',
  'South America',
  'Eastern Africa',
  'Southern Europe',
  'Southern Asia',
  'Western Asia',
  'Northern Africa',
  'South America',
  'Northern Europe',
  'Northern Europe',
  'Western Europe',
  'Western Asia',
  'Central Asia',
  'South-eastern Asia',
  'South-eastern Asia',
  'Western Africa',
  'Polynesia',
  'Polynesia',
  'Caribbean',
  'Northern Africa',
  'Western Asia',
  'Central Asia',
  'Caribbean',
  'Polynesia',
  'Eastern Africa',
  'Eastern Europe',
  'Western Asia',
  'Northern Europe',
  'Eastern Africa',
  'Micronesia',
  'Northern America',
  'Caribbean',
  'South America',
  'Central Asia',
  'Melanesia',
  'South America',
  'South-eastern Asia',
  'Polynesia',
  'Northern Africa',
  'Western Asia',
  'Eastern Africa',
  'Eastern Africa'],
 'Region2': ['',
  '',
  '',
  '',
  '',
  '',
  'Sub-Saharan Africa',
  'Latin America and the Caribbean',
  '',
  'Latin America and the Caribbean',
  'Latin America and the Caribbean',
  '',
  'Latin America and the Caribbean',
  '',
  '',
  '',
  'Latin America and the Caribbean',
  '',
  '',
  'Latin America and the Caribbean',
  '',
  '',
  'Latin America and the Caribbean',
  'Sub-Saharan Africa',
  '',
  '',
  'Latin America and the Caribbean',
  'Latin America and the Caribbean',
  '',
  'Sub-Saharan Africa',
  'Latin America and the Caribbean',
  'Latin America and the Caribbean',
  'Sub-Saharan Africa',
  'Latin America and the Caribbean',
  '',
  '',
  'Sub-Saharan Africa',
  'Sub-Saharan Africa',
  'Sub-Saharan Africa',
  '',
  'Sub-Saharan Africa',
  '',
  'Latin America and the Caribbean',
  'Sub-Saharan Africa',
  'Sub-Saharan Africa',
  'Latin America and the Caribbean',
  '',
  '',
  '',
  '',
  '',
  'Latin America and the Caribbean',
  'Sub-Saharan Africa',
  'Sub-Saharan Africa',
  '',
  'Latin America and the Caribbean',
  'Sub-Saharan Africa',
  '',
  'Latin America and the Caribbean',
  'Latin America and the Caribbean',
  '',
  '',
  '',
  'Sub-Saharan Africa',
  '',
  'Sub-Saharan Africa',
  'Latin America and the Caribbean',
  'Latin America and the Caribbean',
  'Latin America and the Caribbean',
  '',
  'Latin America and the Caribbean',
  'Sub-Saharan Africa',
  'Sub-Saharan Africa',
  '',
  'Sub-Saharan Africa',
  'Sub-Saharan Africa',
  'Latin America and the Caribbean',
  '',
  '',
  '',
  '',
  'Latin America and the Caribbean',
  '',
  'Sub-Saharan Africa',
  'Sub-Saharan Africa',
  'Sub-Saharan Africa',
  '',
  '',
  'Sub-Saharan Africa',
  '',
  '',
  '',
  'Latin America and the Caribbean',
  'Latin America and the Caribbean',
  '',
  'Latin America and the Caribbean',
  'Channel Islands',
  'Sub-Saharan Africa',
  'Sub-Saharan Africa',
  'Latin America and the Caribbean',
  'Latin America and the Caribbean',
  '',
  '',
  'Latin America and the Caribbean',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  'Latin America and the Caribbean',
  '',
  'Channel Islands',
  '',
  '',
  'Sub-Saharan Africa',
  '',
  '',
  '',
  '',
  '',
  '',
  'Sub-Saharan Africa',
  'Sub-Saharan Africa',
  '',
  '',
  '',
  '',
  'Sub-Saharan Africa',
  'Sub-Saharan Africa',
  '',
  '',
  'Sub-Saharan Africa',
  '',
  '',
  'Latin America and the Caribbean',
  'Sub-Saharan Africa',
  'Sub-Saharan Africa',
  'Sub-Saharan Africa',
  'Latin America and the Caribbean',
  '',
  '',
  '',
  '',
  'Latin America and the Caribbean',
  '',
  'Sub-Saharan Africa',
  '',
  'Sub-Saharan Africa',
  '',
  '',
  '',
  '',
  '',
  'Latin America and the Caribbean',
  'Sub-Saharan Africa',
  'Sub-Saharan Africa',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  'Latin America and the Caribbean',
  '',
  'Latin America and the Caribbean',
  'Latin America and the Caribbean',
  '',
  '',
  '',
  '',
  'Latin America and the Caribbean',
  '',
  '',
  '',
  'Sub-Saharan Africa',
  '',
  '',
  'Sub-Saharan Africa',
  'Latin America and the Caribbean',
  'Sub-Saharan Africa',
  'Latin America and the Caribbean',
  'Latin America and the Caribbean',
  'Latin America and the Caribbean',
  '',
  'Latin America and the Caribbean',
  '',
  '',
  'Sub-Saharan Africa',
  'Channel Islands',
  '',
  'Sub-Saharan Africa',
  '',
  'Sub-Saharan Africa',
  'Sub-Saharan Africa',
  '',
  'Latin America and the Caribbean',
  '',
  '',
  '',
  'Sub-Saharan Africa',
  'Sub-Saharan Africa',
  'Latin America and the Caribbean',
  'Sub-Saharan Africa',
  '',
  '',
  '',
  '',
  'Latin America and the Caribbean',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  'Sub-Saharan Africa',
  '',
  '',
  'Latin America and the Caribbean',
  '',
  '',
  '',
  'Latin America and the Caribbean',
  '',
  'Sub-Saharan Africa',
  '',
  '',
  '',
  'Sub-Saharan Africa',
  '',
  '',
  'Latin America and the Caribbean',
  'Latin America and the Caribbean',
  '',
  '',
  'Latin America and the Caribbean',
  '',
  '',
  '',
  '',
  'Sub-Saharan Africa',
  'Sub-Saharan Africa'],
 'Continent': ['Asia',
  'Europe',
  'Europe',
  'Africa',
  'Oceania',
  'Europe',
  'Africa',
  'North America',
  'Antarctica',
  'North America',
  'South America',
  'Asia',
  'North America',
  'Oceania',
  'Europe',
  'Asia',
  'North America',
  'Asia',
  'Asia',
  'North America',
  'Europe',
  'Europe',
  'North America',
  'Africa',
  'North America',
  'Asia',
  'South America',
  'North America',
  'Europe',
  'Africa',
  'South America',
  'South America',
  'Africa',
  'North America',
  'Asia',
  'Europe',
  'Africa',
  'Africa',
  'Africa',
  'Asia',
  'Africa',
  'North America',
  'North America',
  'Africa',
  'Africa',
  'South America',
  'Asia',
  'Asia',
  'Asia',
  'Oceania',
  'Oceania',
  'South America',
  'Africa',
  'Africa',
  'Oceania',
  'North America',
  'Africa',
  'Europe',
  'North America',
  'North America',
  'Asia',
  'Europe',
  'Asia',
  'Africa',
  'Europe',
  'Africa',
  'North America',
  'North America',
  'South America',
  'Africa',
  'North America',
  'Africa',
  'Africa',
  'Europe',
  'Africa',
  'Africa',
  'South America',
  'Europe',
  'Oceania',
  'Europe',
  'Europe',
  'South America',
  'Oceania',
  'Africa',
  'Africa',
  'Africa',
  'Asia',
  'Europe',
  'Africa',
  'Europe',
  'Europe',
  'North America',
  'North America',
  'North America',
  'Oceania',
  'North America',
  'Europe',
  'Africa',
  'Africa',
  'South America',
  'North America',
  'Oceania',
  'Europe',
  'North America',
  'Europe',
  'Europe',
  'Asia',
  'Asia',
  'Asia',
  'Asia',
  'Europe',
  'Europe',
  'Asia',
  'Europe',
  'North America',
  'Asia',
  'Europe',
  'Asia',
  'Asia',
  'Africa',
  'Oceania',
  'Asia',
  'Asia',
  'Asia',
  'Europe',
  'Asia',
  'Africa',
  'Africa',
  'Africa',
  'Europe',
  'Europe',
  'Europe',
  'Africa',
  'Africa',
  'Asia',
  'Asia',
  'Africa',
  'Europe',
  'Oceania',
  'North America',
  'Africa',
  'Africa',
  'Africa',
  'North America',
  'Oceania',
  'Europe',
  'Asia',
  'Europe',
  'North America',
  'Africa',
  'Africa',
  'Asia',
  'Africa',
  'Oceania',
  'Asia',
  'Europe',
  'Oceania',
  'Oceania',
  'North America',
  'Africa',
  'Africa',
  'Oceania',

In [12]:
df_paises = pd.DataFrame(paises_dict)
df_paises.head()

          Country ISO_Code M49_Code          Region1 Region2 Continent
0     Afghanistan      AFG      004    Southern Asia              Asia
1   Åland Islands      ALA      248  Northern Europe            Europe
2         Albania      ALB      008  Southern Europe            Europe
3         Algeria      DZA      012  Northern Africa            Africa
4  American Samoa      ASM      016        Polynesia           Oceania

In [15]:
df_paises.to_csv("../datos/paises.csv",index=False, header=True)

In [16]:
token3=os.getenv("flightlabs_key")

In [18]:
arrivals=pd.read_csv("../datos/cursos_teens.csv", index_col = 0)

In [19]:
arrivals

,Tipo,Duración,Comienzo,Final,Nombre_completo
Destino,,,,,
La Alberca,TEENS,2 WEEKS,07/02/2021,07/16/2021,La Alberca TEENS-VOLUNTEER 2 WEEKS from 07/02/...
La Alberca,TEENS,2 WEEKS,07/09/2021,07/23/2021,La Alberca TEENS-VOLUNTEER 2 WEEKS from 07/09/...
Valverde,TEENS,1 WEEK,07/09/2021,07/16/2021,Valverde TEENS-VOLUNTEER 1 WEEK from 07/09/202...
La Alberca,TEENS,1 WEEK,07/02/2021,07/09/2021,La Alberca TEENS-VOLUNTEER 1 WEEK from 07/02/2...
La Alberca,TEENS,1 WEEK,07/16/2021,07/23/2021,La Alberca TEENS-VOLUNTEER 1 WEEK from 07/16/2...
La Alberca,TEENS,1 WEEK,07/09/2021,07/16/2021,La Alberca TEENS-VOLUNTEER 1 WEEK from 07/09/2...

In [20]:
# Convertir la columna "fecha" a objetos datetime
arrivals["Comienzo"] = pd.to_datetime(arrivals["Comienzo"], format="%m/%d/%Y")

# Usar strftime() para darle el formato deseado a la fecha
arrivals["Comienzo"] = arrivals["Comienzo"].dt.strftime("%Y/%m/%d")

In [21]:
# Convertir la columna "fecha" a objetos datetime
arrivals["Final"] = pd.to_datetime(arrivals["Final"], format="%m/%d/%Y")

# Usar strftime() para darle el formato deseado a la fecha
arrivals["Final"] = arrivals["Final"].dt.strftime("%Y/%m/%d")

In [22]:
arrivals.head()

,Tipo,Duración,Comienzo,Final,Nombre_completo
Destino,,,,,
La Alberca,TEENS,2 WEEKS,2021/07/02,2021/07/16,La Alberca TEENS-VOLUNTEER 2 WEEKS from 07/02/...
La Alberca,TEENS,2 WEEKS,2021/07/09,2021/07/23,La Alberca TEENS-VOLUNTEER 2 WEEKS from 07/09/...
Valverde,TEENS,1 WEEK,2021/07/09,2021/07/16,Valverde TEENS-VOLUNTEER 1 WEEK from 07/09/202...
La Alberca,TEENS,1 WEEK,2021/07/02,2021/07/09,La Alberca TEENS-VOLUNTEER 1 WEEK from 07/02/2...
La Alberca,TEENS,1 WEEK,2021/07/16,2021/07/23,La Alberca TEENS-VOLUNTEER 1 WEEK from 07/16/2...

In [23]:
arrivals=arrivals.reset_index()

In [24]:
arrivals.dtypes

Destino            object
Tipo               object
Duración           object
Comienzo           object
Final              object
Nombre_completo    object
dtype: object

In [25]:
arrivals["Comienzo"] = pd.to_datetime(arrivals["Comienzo"], format="%Y/%m/%d")

# Verificar el tipo de datos de la columna "fecha"
print(arrivals["Comienzo"].dtype)

datetime64[ns]

In [26]:

api_call_fecha=pd.DataFrame (arrivals['Comienzo']-timedelta(days=1)+timedelta(days=365))
type(api_call_fecha)
api_call_fecha

    Comienzo
0 2022-07-01
1 2022-07-08
2 2022-07-08
3 2022-07-01
4 2022-07-15
5 2022-07-08

In [27]:
api_call_fecha=api_call_fecha.drop_duplicates()
api_call_fecha

    Comienzo
0 2022-07-01
1 2022-07-08
4 2022-07-15

In [28]:
"""def call_api(date):
  
    date = str(date).split()[0]
    print(date)
    api_result = requests.get(f'https://app.goflightlabs.com/historical/{date}?access_key={token3}&code=MAD&type=arrival')
    return api_result.json()

# Aplicar la función a la columna "Comienzo" del DataFrame
#arrivals["api_results"] = arrivals["Comienzo"].apply(call_api)

arrivals_data = api_call_fecha['Comienzo'].apply(call_api)"""

'def call_api(date):\n  \n    date = str(date).split()[0]\n    print(date)\n    api_result = requests.get(f\'https://app.goflightlabs.com/historical/{date}?access_key={token3}&code=MAD&type=arrival\')\n    return api_result.json()\n\n# Aplicar la función a la columna "Comienzo" del DataFrame\n#arrivals["api_results"] = arrivals["Comienzo"].apply(call_api)\n\narrivals_data = api_call_fecha[\'Comienzo\'].apply(call_api)'

In [29]:
with open("../datos/arrivals_data.pickle", "rb") as f:
    data_flight = pickle.load(f)

In [30]:
flight_data_list = []
for data in data_flight[0]['data']:
    flight_data = {}
    if 'terminal' in data['arrival']:
        flight_data["terminal"] = data['arrival']['terminal']
    else:
        flight_data["terminal"] = "No se ha encontrado la terminal de llegada."
    if 'scheduledTime' in data['arrival']:
        flight_data["scheduledTime"] = data['arrival']['scheduledTime']
    else:
        flight_data["scheduledTime"] = "No se ha encontrado el horario programado."
    if 'name' in data['airline']:
        flight_data["airlineName"] = data['airline']['name']
    else:
        flight_data["airlineName"] = "No se ha encontrado el nombre de la aerolínea."
    if 'iataCode' in data['airline']:
        flight_data["iataCode"] = data['airline']['iataCode']
    else:
        flight_data["iataCode"] = "No se ha encontrado el código IATA de la aerolínea."
    if 'number' in data['flight']:
        flight_data["flightNumber"] = data['flight']['number']
    else:
        flight_data["flightNumber"] = "No se ha encontrado el número del vuelo."
    if 'iataNumber' in data['flight']:
        flight_data["iataNumber"] = data['flight']['iataNumber']
    else:
        flight_data["iataNumber"] = "No se ha encontrado el número IATA del vuelo."
    flight_data_list.append(flight_data)
flight_data_df = pd.DataFrame(flight_data_list)
flight_data_df

,terminal,scheduledTime,airlineName,iataCode,flightNumber,iataNumber
0,4s,2022-07-01t04:10:00.000,american airlines,aa,8800,aa8800
1,4s,2022-07-01t04:10:00.000,qatar airways,qr,6560,qr6560
2,4s,2022-07-01t04:10:00.000,british airways,ba,7107,ba7107
3,4s,2022-07-01t04:10:00.000,vueling,vy,5272,vy5272
4,4s,2022-07-01t04:10:00.000,iberia,ib,3329,ib3329
...,...,...,...,...,...,...
1660,No se ha encontrado la terminal de llegada.,2022-07-01t19:50:00.000,iberia,ib,2167,ib2167
1661,No se ha encontrado la terminal de llegada.,2022-07-01t16:51:00.000,iberia,ib,7053,ib7053
1662,No se ha encontrado la terminal de llegada.,2022-07-01t22:35:00.000,air europa,ux,4050,ux4050
1663,4s,2022-07-01t23:59:00.000,iberia express,i2,3717,i23717
1664,No se ha encontrado la terminal de llegada.,2022-07-02t01:49:00.000,iberia,ib,2,ib2

In [31]:
#Definimos una funcion para separar el scheduledTime en scheduledDay y la hora y luego lo applicamos a la columna
def split_scheduled_time(scheduled_time):
    if scheduled_time == "No se ha encontrado el horario programado.":
        return ("No se pudo separar", "No se ha encontrado el horario programado")
    else:
        scheduled_day, scheduled_time = scheduled_time.split("t")
        return scheduled_day, scheduled_time

flight_data_df["scheduledDay"], flight_data_df["scheduledTime"] = zip(*flight_data_df["scheduledTime"].apply(split_scheduled_time))

In [32]:
flight_data_df

,terminal,scheduledTime,airlineName,iataCode,flightNumber,iataNumber,scheduledDay
0,4s,04:10:00.000,american airlines,aa,8800,aa8800,2022-07-01
1,4s,04:10:00.000,qatar airways,qr,6560,qr6560,2022-07-01
2,4s,04:10:00.000,british airways,ba,7107,ba7107,2022-07-01
3,4s,04:10:00.000,vueling,vy,5272,vy5272,2022-07-01
4,4s,04:10:00.000,iberia,ib,3329,ib3329,2022-07-01
...,...,...,...,...,...,...,...
1660,No se ha encontrado la terminal de llegada.,19:50:00.000,iberia,ib,2167,ib2167,2022-07-01
1661,No se ha encontrado la terminal de llegada.,16:51:00.000,iberia,ib,7053,ib7053,2022-07-01
1662,No se ha encontrado la terminal de llegada.,22:35:00.000,air europa,ux,4050,ux4050,2022-07-01
1663,4s,23:59:00.000,iberia express,i2,3717,i23717,2022-07-01
1664,No se ha encontrado la terminal de llegada.,01:49:00.000,iberia,ib,2,ib2,2022-07-02

In [33]:
flight_data_df.to_csv("../datos/vuelos.csv",index=False, header=True)